from cohere.responses.classify import Example

examples = [
    Example("Hola, me gustaría generar una preconsulta", "Generate Pre-consult"),
    Example("Quiero crear mi documento", "Generate Pre-consult"),
    Example("Necesito una pre consulta para podersela dar a mi medico","Generate Pre-consult"),
    Example("¿Cómo puedo programar una preconsulta?", "Generate Pre-consult"),
    Example("Estoy interesado en programar una preconsulta",
            "Generate Pre-consult"),
    Example("Quiero saber más sobre las preconsultas", "Generate Pre-consult"),
    Example("¿Cómo puedo obtener una preconsulta?", "Generate Pre-consult"),
    Example("Necesito una preconsulta para mi mamá", "Generate Pre-consult"),
    Example("Quiero programar una preconsulta para la semana que viene",
            "Generate Pre-consult"),
    Example("¿Cómo puedo pagar por una preconsulta?", "Generate Pre-consult"),
    Example("Quiero reservar una preconsulta para el Dr. González",
            "Generate Pre-consult"),
    Example("¿Qué información necesito para reservar una preconsulta?",
            "Generate Pre-consult"),
    Example("Necesito programar una preconsulta lo antes posible",
            "Generate Pre-consult"),
    Example("¿Cuál es el proceso para programar una preconsulta?",
            "Generate Pre-consult"),
    Example("Quiero programar una preconsulta para mi hijo",
            "Generate Pre-consult"),
    Example("Me gustaría agendar una cita médica", "Generate Pre-consult"),
    Example("¿Cuánto cuesta una preconsulta?", "Generate Pre-consult"),
    Example("Quiero programar una preconsulta para mi esposo",
            "Generate Pre-consult"),
    Example("¿Tienen disponibilidad para una preconsulta mañana?",
            "Generate Pre-consult"),
    Example("Quiero programar una preconsulta para un especialista en cardiología",
            "Generate Pre-consult"),
    Example("¿Hay algún descuento para las preconsultas?",
            "Generate Pre-consult"),
    Example("Quiero programar una preconsulta en línea", "Generate Pre-consult"),
    Example("¿Puedo cancelar mi preconsulta?", "Generate Pre-consult"),
    Example("Quiero programar una preconsulta para la Dra. Sánchez",
            "Generate Pre-consult"),
    Example("Mónica Salazar García", "Name"),
    Example("Raúl Fernández Guzmán", "Name"),
    Example("Ana González López", "Name"),
    Example("Luisa Torres Ramírez", "Name"),
    Example("Mario Espinoza Hernández", "Name"),
    Example("Sofía Pérez Gómez", "Name"),
    Example("Ernesto Rodríguez Rivera", "Name"),
    Example("Mariana Martínez Díaz", "Name"),
    Example("Gustavo Sánchez Núñez", "Name"),
    Example("Paula Hernández Castro", "Name"),
    Example("26", "Age"),
    Example("42", "Age"),
    Example("33", "Age"),
    Example("58", "Age"),
    Example("21", "Age"),
    Example("47", "Age"),
    Example("39", "Age"),
    Example("64", "Age"),
    Example("31", "Age"),
    Example("55", "Age"),
    Example("Monterrey, Nuevo León", "Place of birth"),
    Example("Guadalajara, Jalisco", "Place of birth"),
    Example("Tijuana, Baja California", "Place of birth"),
    Example("Puebla, Puebla", "Place of birth"),
    Example("Culiacán, Sinaloa", "Place of birth"),
    Example("Morelia, Michoacán", "Place of birth"),
    Example("Cancún, Quintana Roo", "Place of birth"),
    Example("Tuxtla Gutiérrez, Chiapas", "Place of birth"),
    Example("Ciudad Obregón, Sonora", "Place of birth"),
    Example("Toluca, Estado de México", "Place of birth"),
    Example("Mexicali, Baja California", "Place of birth"),
    Example("Acapulco, Guerrero", "Place of birth"),
    Example("San Luis Potosí, San Luis Potosí", "Place of birth"),
    Example("Oaxaca, Oaxaca", "Place of birth"),
    Example("Mazatlán, Sinaloa", "Place of birth"),
    Example("Campeche, Campeche", "Place of birth"),
    Example("Tampico, Tamaulipas", "Place of birth"),
    Example("Veracruz, Veracruz", "Place of birth"),
    Example("Hermosillo, Sonora", "Place of birth"),
    Example("Zacatecas, Zacatecas", "Place of birth"),
    Example("AMYG990603HSPRRS08", "Personal id"),
    Example("BEVA921013MGTRVR05", "Personal id"),
    Example("CARO751007HTSRRS08", "Personal id"),
    Example("DAGA770731HSPRFL01", "Personal id"),
    Example("EVES990223HSPRNS06", "Personal id"),
    Example("FLOR940511MSPTSN01", "Personal id"),
    Example("GAMA800123HSPNLC09", "Personal id"),
    Example("HERN940922HTSPYR09", "Personal id"),
    Example("IZAB840222MTSPRR07", "Personal id"),
    Example("JOMA900606HSPGNL08", "Personal id"),
    Example("KUNI780117HSPGNS08", "Personal id"),
    Example("LIRA950713HTSRLS04", "Personal id"),
    Example("MEZA910303MSPPRR06", "Personal id"),
    Example("NARA860619MTSPLN00", "Personal id"),
    Example("ORTE800307HSPRTN05", "Personal id"),
    Example("PERE940709HSPRRS00", "Personal id"),
    Example("RAMI830615HTSPDD02", "Personal id"),
    Example("SANC800108HSPNYL01", "Personal id"),
    Example("TORR790125HSPHVM08", "Personal id"),
    Example("VALD830424MTSRLN07", "Personal id"),
    Example("8265754321", "Phone"),
    Example("6259648374", "Phone"),
    Example("7539182465", "Phone"),
    Example("4493165728", "Phone"),
    Example("6678219453", "Phone"),
    Example("8334756921", "Phone"),
    Example("5582473698", "Phone"),
    Example("7126459834", "Phone"),
    Example("9257148365", "Phone"),
    Example("3549862710", "Phone"),
    Example("8993617265", "Phone"),
    Example("5613479258", "Phone"),
    Example("7194836251", "Phone"),
    Example("4738269150", "Phone"),
    Example("6351728409", "Phone"),
    Example("8946152370", "Phone"),
    Example("3258749601", "Phone"),
    Example("7806392415", "Phone"),
    Example("9416837520", "Phone"),
    Example("1684937520", "Phone"),
]
